name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  retags:
    permissions:
      packages: write
    runs-on: ubuntu-22.04    
    steps:
      - uses: actions/checkout@v3

      - name: Test Retags
        id: broker
        uses: ./
        with:
          broker_jwt: ${{ secrets.BROKER_JWT }}
          provision_role_id: ${{ secrets.PROVISION_ROLE }}
          project_name: client
          app_name: app-client
          environment: development

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: https://vault-iit.apps.silver.devops.gov.bc.ca
          token: ${{ steps.broker.outputs.vault_token }}
          exportEnv: 'false'
          secrets: |
            apps/data/${{ secrets.SECRET_PATH}} sample | SAMPLE;

      - name: Checks
        run: echo ${{ steps.secrets.outputs.SAMPLE }}